### ISSUE TITLE
Error being received using Express and this package is a dependency

### ISSUE THREAD

**Issue by ccit-spence** [isaacs/core-util-is#4]
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

util.js:35
  var str = String(f).replace(formatRegExp, function(x) {
                      ^
RangeError: Maximum call stack size exceeded

**Comment by isaacs** [comment]
I don't think that's an issue with this module.  that line of code doesn't exist in this module.  I think you're looking for some file named `util.js` in Express somewhere.
