### ISSUE TITLE
Error to install by npm 

### ISSUE THREAD

**Issue by mitsuishihidemi** [isaacs/core-util-is#7]
Hi, 

I got this error when i try to intall this module by npm install.

npm ERR! Error: ENOENT, open '/Users/mitsuishihidemi/idea/artifacts/ui_war_exploded/v3/node_modules/core-util-is/package.json'

can someone help me?

thanks

**Comment by isaacs** [comment]
I dont think this is an issue with this module.  Can you install other things? Maybe run `npm cache clean` and try again?
